import React, { useState, useEffect } from 'react';
import offerLetterAPI from '../../../services/offerLetterAPI';
import { offerLetterPDFService } from '../../../services/offerLetterPDFService';
import { HiOutlineDocumentText, HiOutlineArrowDownTray, HiOutlineEye } from "react-icons/hi2";
import './MyDocuments.css';

const MyDocuments = () => {
  const [letters, setLetters] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchLetters = async () => {
      try {
        const res = await offerLetterAPI.getMyOfferLetters();
        setLetters(res.data.letters || []);
      } catch (err) {
        console.error("Error fetching offer letters:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchLetters();
  }, []);

  const handleDownload = (formData) => {
    offerLetterPDFService.downloadOfferLetter(formData);
  };

  const handleView = (formData) => {
    offerLetterPDFService.viewOfferLetter(formData);
  };

  if (loading) {
    return (
      <div className="docs-loading">
        <div className="spinner"></div>
        <p>Loading your documents...</p>
      </div>
    );
  }

  return (
    <div className="my-docs-container">
      <div className="docs-header">
        <h1>My Documents</h1>
        <p>View and download your official company documents.</p>
      </div>

      <div className="docs-list">
        {letters.length > 0 ? (
          letters.map((letter) => (
            <div key={letter.id} className="doc-card">
              <div className="doc-icon-container">
                <HiOutlineDocumentText className="doc-icon" />
              </div>
              <div className="doc-info">
                <h3>Offer Letter</h3>
                <p>Issued on: {new Date(letter.issue_date).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</p>
              </div>
              <div className="doc-actions">
                <button 
                  className="doc-view-btn"
                  onClick={() => handleView(letter.form_data)}
                  title="View PDF"
                >
                  <HiOutlineEye size={20} />
                  <span>View</span>
                </button>
                <button 
                  className="doc-download-btn"
                  onClick={() => handleDownload(letter.form_data)}
                  title="Download PDF"
                >
                  <HiOutlineArrowDownTray size={20} />
                  <span>Download</span>
                </button>
              </div>
            </div>
          ))
        ) : (
          <div className="no-docs">
            <HiOutlineDocumentText size={48} />
            <h3>No documents found</h3>
            <p>Your offer letter will appear here once it's generated by HR.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default MyDocuments;
